# Generated by Django 4.2.9 on 2024-01-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='release title')),
                ('date', models.DateField(verbose_name='date released')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=400, verbose_name='item URL')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='total price')),
                ('track_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='track price')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.release')),
            ],
        ),
    ]
