# Generated by Django 4.2.9 on 2024-01-24 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
        migrations.AddField(
            model_name='release',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
    ]
